name: dao
description: A starting point for Dart Process Api package, for Using commondline app to Easyly access start stop restart commands, see demo or examples.
version: 0.0.4
homepage: https://gitee.com/darto/dao

## pub publish --server=https://pub.dartlang.org

environment:
  sdk: '>=2.8.1 <3.0.0'

dependencies:
  convert: ^2.1.1
  mongo_dart: ^0.4.2
  alm: ^0.0.6
